stages:
  - build
  - publish

osx-build:
  stage: build
  image: rust:latest
  variables:
    TARGET: x86_64-apple-darwin
  only:
    - tags
  script:
    - rustup target add $TARGET
    - cargo build --release --target $TARGET
  artifacts:
    expire_in: 1 hour
    paths:
      - target/$TARGET/main

osx-publish:
    image: inetprocess/gitlab-release
    stage: publish
    variables:
      TARGET: x86_64-apple-darwin
    only:
        - tags
    script:
        - gitlab-release --message $CI_COMMIT_TAG target/$TARGET/main