stages:
  - test
  - pre-publish
  - publish

test-rust-latest:
  stage: test
  image: rust:latest
  script:
    - cargo build --verbose
    - cargo test --verbose

test-rust-nightly:
  stage: test
  image: rustlang/rust:nightly
  script:
    - cargo build --verbose
    - cargo test --verbose
  allow_failure: true

pre-publish:
    stage: pre-publish
    image: rust:latest
    script:
        - cargo build --release
    artifacts:
        expire_in: '1 hour'
        paths:
            - target/release/main
publish:
    image: inetprocess/gitlab-release
    stage: publish
    only:
        - tags
    script:
        - gitlab-release --message 'New release' target/release/main